Fix error with rubygems-update
```
ERROR:  Error installing rubygems-update:
	There are no versions of rubygems-update (= 3.4.3) compatible with your Ruby & RubyGems
	rubygems-update requires Ruby version >= 2.6.0. The current ruby version is 2.5.9.229.
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ dir_chdir - /usr/local/bundle/gems/rubygems-update-3.0.3
```

Same issue as https://github.com/rubygems/rubygems/issues/2534,
following the suggested workaround in the comments there to install an
older version of rubygems-update